import { db } from '@/db';
import { auditLogs } from '@/db/schema';

async function main() {
    const sampleAuditLogs = [
        // Entry Created logs (8 entries)
        {
            action: 'entry_created',
            entityType: 'entry',
            entityId: 'entry_abc123',
            userId: 'user_123',
            ipAddress: '192.168.1.100',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
            metadata: JSON.stringify({ title: 'Morning thoughts', wordCount: 245, tags: ['personal', 'morning'] }),
            createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000 - 2 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'entry_created',
            entityType: 'entry',
            entityId: 'entry_xyz789',
            userId: 'user_456',
            ipAddress: '10.0.0.50',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            metadata: JSON.stringify({ title: 'Project ideas', wordCount: 512, tags: ['work', 'brainstorm'] }),
            createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 - 5 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'entry_created',
            entityType: 'entry',
            entityId: 'entry_def456',
            userId: null,
            ipAddress: '172.16.0.25',
            userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15',
            metadata: JSON.stringify({ title: 'Weekend plans', wordCount: 189, tags: ['personal', 'weekend'] }),
            createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 - 8 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'entry_created',
            entityType: 'entry',
            entityId: 'entry_ghi789',
            userId: 'user_789',
            ipAddress: '192.168.1.101',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
            metadata: JSON.stringify({ title: 'Learning goals for 2024', wordCount: 678, tags: ['goals', 'learning'] }),
            createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 - 3 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'entry_created',
            entityType: 'entry',
            entityId: 'entry_jkl012',
            userId: 'user_123',
            ipAddress: '192.168.1.100',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
            metadata: JSON.stringify({ title: 'Daily reflection', wordCount: 423, tags: ['reflection', 'daily'] }),
            createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 - 6 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'entry_created',
            entityType: 'entry',
            entityId: 'entry_mno345',
            userId: null,
            ipAddress: '10.0.0.51',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            metadata: JSON.stringify({ title: 'Book notes', wordCount: 891, tags: ['reading', 'notes'] }),
            createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 - 9 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'entry_created',
            entityType: 'entry',
            entityId: 'entry_pqr678',
            userId: 'user_456',
            ipAddress: '10.0.0.50',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            metadata: JSON.stringify({ title: 'Meeting summary', wordCount: 334, tags: ['work', 'meeting'] }),
            createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 - 4 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'entry_created',
            entityType: 'entry',
            entityId: 'entry_stu901',
            userId: 'user_789',
            ipAddress: '192.168.1.102',
            userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15',
            metadata: JSON.stringify({ title: 'Gratitude journal', wordCount: 156, tags: ['gratitude', 'personal'] }),
            createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
        },

        // Entry Updated logs (9 entries)
        {
            action: 'entry_updated',
            entityType: 'entry',
            entityId: 'entry_abc123',
            userId: 'user_123',
            ipAddress: '192.168.1.100',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
            metadata: JSON.stringify({ changes: ['title', 'content'], previousWordCount: 245, newWordCount: 312 }),
            createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 - 7 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'entry_updated',
            entityType: 'entry',
            entityId: 'entry_xyz789',
            userId: 'user_456',
            ipAddress: '10.0.0.50',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            metadata: JSON.stringify({ changes: ['content'], previousWordCount: 512, newWordCount: 587 }),
            createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 - 1 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'entry_updated',
            entityType: 'entry',
            entityId: 'entry_def456',
            userId: null,
            ipAddress: '172.16.0.25',
            userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15',
            metadata: JSON.stringify({ changes: ['tags'], previousWordCount: 189, newWordCount: 189 }),
            createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 - 10 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'entry_updated',
            entityType: 'entry',
            entityId: 'entry_ghi789',
            userId: 'user_789',
            ipAddress: '192.168.1.101',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
            metadata: JSON.stringify({ changes: ['content', 'tags'], previousWordCount: 678, newWordCount: 745 }),
            createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 - 5 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'entry_updated',
            entityType: 'entry',
            entityId: 'entry_jkl012',
            userId: 'user_123',
            ipAddress: '192.168.1.100',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
            metadata: JSON.stringify({ changes: ['title'], previousWordCount: 423, newWordCount: 423 }),
            createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 - 11 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'entry_updated',
            entityType: 'entry',
            entityId: 'entry_mno345',
            userId: null,
            ipAddress: '10.0.0.51',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            metadata: JSON.stringify({ changes: ['content'], previousWordCount: 891, newWordCount: 1023 }),
            createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 - 2 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'entry_updated',
            entityType: 'entry',
            entityId: 'entry_pqr678',
            userId: 'user_456',
            ipAddress: '10.0.0.50',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            metadata: JSON.stringify({ changes: ['content', 'title'], previousWordCount: 334, newWordCount: 389 }),
            createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 - 1 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'entry_updated',
            entityType: 'entry',
            entityId: 'entry_stu901',
            userId: 'user_789',
            ipAddress: '192.168.1.102',
            userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15',
            metadata: JSON.stringify({ changes: ['content'], previousWordCount: 156, newWordCount: 203 }),
            createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'entry_updated',
            entityType: 'entry',
            entityId: 'entry_abc123',
            userId: 'user_123',
            ipAddress: '192.168.1.100',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
            metadata: JSON.stringify({ changes: ['tags'], previousWordCount: 312, newWordCount: 312 }),
            createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        },

        // Entry Deleted logs (3 entries)
        {
            action: 'entry_deleted',
            entityType: 'entry',
            entityId: 'entry_old123',
            userId: 'user_456',
            ipAddress: '10.0.0.50',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            metadata: JSON.stringify({ title: 'Old draft ideas', deletedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString() }),
            createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 - 6 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'entry_deleted',
            entityType: 'entry',
            entityId: 'entry_old456',
            userId: null,
            ipAddress: '172.16.0.25',
            userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15',
            metadata: JSON.stringify({ title: 'Temporary notes', deletedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString() }),
            createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 - 5 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'entry_deleted',
            entityType: 'entry',
            entityId: 'entry_old789',
            userId: 'user_789',
            ipAddress: '192.168.1.101',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
            metadata: JSON.stringify({ title: 'Outdated thoughts', deletedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString() }),
            createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 - 7 * 60 * 60 * 1000).toISOString(),
        },

        // Entry Viewed logs (6 entries)
        {
            action: 'entry_viewed',
            entityType: 'entry',
            entityId: 'entry_abc123',
            userId: 'user_123',
            ipAddress: '192.168.1.100',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
            metadata: JSON.stringify({ duration: 45, viewMode: 'read' }),
            createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 - 4 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'entry_viewed',
            entityType: 'entry',
            entityId: 'entry_xyz789',
            userId: 'user_456',
            ipAddress: '10.0.0.50',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            metadata: JSON.stringify({ duration: 82, viewMode: 'edit' }),
            createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 - 2 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'entry_viewed',
            entityType: 'entry',
            entityId: 'entry_ghi789',
            userId: null,
            ipAddress: '192.168.1.101',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
            metadata: JSON.stringify({ duration: 156, viewMode: 'read' }),
            createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 - 8 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'entry_viewed',
            entityType: 'entry',
            entityId: 'entry_jkl012',
            userId: 'user_123',
            ipAddress: '192.168.1.100',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
            metadata: JSON.stringify({ duration: 34, viewMode: 'read' }),
            createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 - 3 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'entry_viewed',
            entityType: 'entry',
            entityId: 'entry_mno345',
            userId: 'user_789',
            ipAddress: '192.168.1.102',
            userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15',
            metadata: JSON.stringify({ duration: 67, viewMode: 'edit' }),
            createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 - 6 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'entry_viewed',
            entityType: 'entry',
            entityId: 'entry_pqr678',
            userId: null,
            ipAddress: '10.0.0.50',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            metadata: JSON.stringify({ duration: 123, viewMode: 'read' }),
            createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
        },

        // Draft Auto-Saved logs (7 entries)
        {
            action: 'draft_auto_saved',
            entityType: 'draft',
            entityId: 'draft_temp_123',
            userId: 'user_123',
            ipAddress: '192.168.1.100',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
            metadata: JSON.stringify({ wordCount: 123, autosaveVersion: 1 }),
            createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000 - 3 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'draft_auto_saved',
            entityType: 'draft',
            entityId: 'draft_temp_123',
            userId: 'user_123',
            ipAddress: '192.168.1.100',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
            metadata: JSON.stringify({ wordCount: 187, autosaveVersion: 2 }),
            createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000 - 2 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'draft_auto_saved',
            entityType: 'draft',
            entityId: 'draft_temp_456',
            userId: 'user_456',
            ipAddress: '10.0.0.50',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            metadata: JSON.stringify({ wordCount: 234, autosaveVersion: 1 }),
            createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 - 6 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'draft_auto_saved',
            entityType: 'draft',
            entityId: 'draft_temp_789',
            userId: null,
            ipAddress: '172.16.0.25',
            userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15',
            metadata: JSON.stringify({ wordCount: 89, autosaveVersion: 1 }),
            createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 - 9 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'draft_auto_saved',
            entityType: 'draft',
            entityId: 'draft_temp_789',
            userId: null,
            ipAddress: '172.16.0.25',
            userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15',
            metadata: JSON.stringify({ wordCount: 145, autosaveVersion: 2 }),
            createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 - 8 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'draft_auto_saved',
            entityType: 'draft',
            entityId: 'draft_temp_101',
            userId: 'user_789',
            ipAddress: '192.168.1.101',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
            metadata: JSON.stringify({ wordCount: 456, autosaveVersion: 3 }),
            createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 - 4 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'draft_auto_saved',
            entityType: 'draft',
            entityId: 'draft_temp_202',
            userId: 'user_123',
            ipAddress: '192.168.1.100',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
            metadata: JSON.stringify({ wordCount: 78, autosaveVersion: 1 }),
            createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
        },

        // Mode Switched logs (4 entries)
        {
            action: 'mode_switched',
            entityType: 'system',
            entityId: null,
            userId: 'user_123',
            ipAddress: '192.168.1.100',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
            metadata: JSON.stringify({ from: 'light', to: 'dark' }),
            createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 - 9 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'mode_switched',
            entityType: 'system',
            entityId: null,
            userId: null,
            ipAddress: '10.0.0.50',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            metadata: JSON.stringify({ from: 'edit', to: 'read' }),
            createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 - 7 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'mode_switched',
            entityType: 'system',
            entityId: null,
            userId: 'user_456',
            ipAddress: '10.0.0.50',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            metadata: JSON.stringify({ from: 'dark', to: 'light' }),
            createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 - 8 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'mode_switched',
            entityType: 'system',
            entityId: null,
            userId: 'user_789',
            ipAddress: '192.168.1.102',
            userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15',
            metadata: JSON.stringify({ from: 'read', to: 'edit' }),
            createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 - 2 * 60 * 60 * 1000).toISOString(),
        },

        // App Loaded logs (3 entries)
        {
            action: 'app_loaded',
            entityType: 'system',
            entityId: null,
            userId: 'user_123',
            ipAddress: '192.168.1.100',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
            metadata: JSON.stringify({ version: '1.0.0', loadTime: 234 }),
            createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000 - 1 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'app_loaded',
            entityType: 'system',
            entityId: null,
            userId: null,
            ipAddress: '172.16.0.25',
            userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15',
            metadata: JSON.stringify({ version: '1.0.0', loadTime: 412 }),
            createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 - 11 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'app_loaded',
            entityType: 'system',
            entityId: null,
            userId: 'user_456',
            ipAddress: '10.0.0.50',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            metadata: JSON.stringify({ version: '1.0.0', loadTime: 189 }),
            createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 - 9 * 60 * 60 * 1000).toISOString(),
        },

        // Search Performed logs (4 entries)
        {
            action: 'search_performed',
            entityType: 'system',
            entityId: null,
            userId: 'user_123',
            ipAddress: '192.168.1.100',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
            metadata: JSON.stringify({ query: 'morning routine', resultsCount: 5 }),
            createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 - 5 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'search_performed',
            entityType: 'system',
            entityId: null,
            userId: null,
            ipAddress: '10.0.0.50',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            metadata: JSON.stringify({ query: 'project ideas', resultsCount: 12 }),
            createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 - 4 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'search_performed',
            entityType: 'system',
            entityId: null,
            userId: 'user_789',
            ipAddress: '192.168.1.101',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
            metadata: JSON.stringify({ query: 'learning goals', resultsCount: 3 }),
            createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 - 7 * 60 * 60 * 1000).toISOString(),
        },
        {
            action: 'search_performed',
            entityType: 'system',
            entityId: null,
            userId: 'user_456',
            ipAddress: '10.0.0.50',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            metadata: JSON.stringify({ query: 'gratitude', resultsCount: 8 }),
            createdAt: new Date(Date.now() - 15 * 60 * 60 * 1000).toISOString(),
        },
    ];

    await db.insert(auditLogs).values(sampleAuditLogs);
    
    console.log('✅ Audit logs seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});